# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: Cake@2
  displayName: 'Build & Package'
  inputs: 
    script: '$(Build.SourcesDirectory)/build.cake'
    target: 'Default'
    verbosity: 'Verbose'
    arguments: '--path=$(System.DefaultWorkingDirectory)'
    useBuildAgentNuGetExe: true
- task: PowerShell@2
  displayName : 'Publish Package'
  inputs:
    filePath: '$(Build.SourcesDirectory)/publish-package.ps1'
    arguments: -path $(System.DefaultWorkingDirectory)
